[package]
name = "rust9cc"
version = "0.1.0"
authors = ["xeno14 <integral14.dev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
clap = "2.33.3"
thiserror = "1.0"